- raft/bootstrap.go
- raft/log.go
- raft/raft.go
raft commit offset if ahead of stable entries after #313
> fix(store): raft commit ahead of stable entries

- internal/trigger/trigger/trigger.go
> fix: trigger write retry and dl event

- internal/timer/timingwheel/timingwheel.go
> fix: fix metadata recover logic

- go.mod
- go.sum
- internal/primitive/transform/action/action.go
- internal/primitive/transform/action/action_bench_test.go
- internal/primitive/transform/action/math_action_test.go
- internal/primitive/transform/action/regex_action_test.go
- internal/primitive/transform/action/string_action_test.go
- internal/primitive/transform/action/struct_action_test.go
- internal/primitive/transform/action/time_action.go
- internal/primitive/transform/action/time_action_test.go
- internal/primitive/transform/function/format_functions.go
- internal/primitive/transform/function/util/time.go
- internal/primitive/transform/function/util/time_test.go
- change function format_date to date_format
- function date_format remove fromFormat param which use default format RFC3339, and add param timeZone which default is UTC
- change function format_unix_time to unix_time_format
- unix_time_format add param timeZone which default is UTC
- change date format  from YYYY-mm-dd HH:MM:SS to Y-m-d H:i:s
> refactor: change format date function

- cmd/controller/main.go
- cmd/gateway/main.go
- cmd/store/main.go
- cmd/timer/main.go
- cmd/trigger/main.go
- config/controller.yaml.example
- config/gateway.yaml.example
- config/store.yaml.example
- config/timer.yaml.example
- config/trigger.yaml.example
- internal/controller/config.go
- internal/gateway/config.go
- internal/store/config.go
- internal/timer/config.go
- internal/trigger/config.go
- observability/observability.go
- observability/tracing/tracing.go
Signed-off-by: wenfeng <sxian.wang@gmail.com>
Issue Number: close N/a
add observability config
> feat: add observability config

- go.mod
- go.sum
- internal/raft/log/log_storage.go
- internal/trigger/reader/reader.go
- internal/trigger/util/event.go
Issue Number: close N/a
change JSON path library, https://cburgmer.github.io/json-path-comparison/
https://cburgmer.github.io/json-path-comparison/
> feat: change json path library

- internal/primitive/transform/arg/arg.go
- internal/primitive/transform/arg/arg_test.go
- internal/primitive/transform/arg/event.go
- internal/trigger/transform/template/exec.go
- internal/trigger/transform/template/exec_test.go
- internal/trigger/transform/template/node.go
- internal/trigger/transform/template/parse.go
- internal/trigger/transform/template/parse_test.go
- internal/trigger/transform/transformer.go
- internal/trigger/transform/transformer_test.go
- transformer template support event attribute `<$.attributeName>` and data `<$.data.key>`
- fix newArg event attribute such as  `$.dataxxx` as event data bug
> feat: transformer template support json path

- cmd/controller/main.go
- internal/controller/trigger/controller.go
- internal/controller/trigger/controller_test.go
- internal/store/segment/server.go
- pkg/cluster/controller.go
Signed-off-by: wenfeng <sxian.wang@gmail.com>
Controller can not start due to the wrong condition
> fix: controller can not start

- internal/primitive/transform/action/action.go
- internal/primitive/transform/action/condition_if_action.go
- internal/primitive/transform/action/condition_if_action_test.go
- internal/primitive/transform/action/regex_action.go
- internal/primitive/transform/action/struct_action.go
- internal/primitive/transform/common/cast.go
- internal/primitive/transform/common/types.go
- internal/primitive/transform/function/format_functions.go
- internal/primitive/transform/function/function.go
- internal/primitive/transform/function/math_functions.go
- internal/primitive/transform/function/strings_functions.go
-  add transformer function condition if, it's used like below:
```json
["condition_if","$.targetPath","$.path","op","compareValue","trueValue","falseValue"]
```
op only support `==, >=, >, <=, <`
> feat: add transformer function condition if

- pkg/cluster/raw_client/conn.go
```
time="2022-12-20T15:16:32Z" level=warning msg="failed to GetAppendableSegment" error="rpc error: code = Unknown desc = {\"code\":9700,\"message\":\"i'm not leader, please connect to: vanus-controller-2.vanus-controller.vanus.svc:2048\"}" req="event_log_id:3254845456 limited:1" res="<nil>"
time="2022-12-20T15:16:32Z" level=warning msg="invoke error, try to retry" error="rpc error: code = Unknown desc = {\"code\":9700,\"message\":\"i'm not leader, please connect to: vanus-controller-2.vanus-controller.vanus.svc:2048\"}"
time="2022-12-20T15:16:32Z" level=warning msg="invoke error" error="rpc error: code = Unknown desc = {\"code\":9700,\"message\":\"i'm not leader, please connect to: vanus-controller-2.vanus-controller.vanus.svc:2048\"}"
``` …
> fix: the route cannot be updated after the controller leader switched

- internal/store/block/block.go
- internal/store/block/raft/appender.go
- internal/store/segment/mock_replica.go
- internal/store/segment/mock_server.go
- internal/store/segment/replica.go
- internal/store/segment/server.go
- raft/inflight.go
- raft/log.go
- raft/log_unstable.go
- raft/node.go
- raft/propose.go
- raft/raft.go
Issue Number: close #241
Append events to store returns negative true when the leader node becomes a follower.
Support callback for raft proposing to watch the entry is committed or dropped.
> feat(store): raft support propose callback

- raft/raft.go
local commit of raft leader not advance sometimes after #313
> fix: raft local commit not advance sometimes

- internal/store/vsb/block_append.go
Recursive calls cause io worker exhaustion.
Create new goroutine.
> fix(store): recursive calls cause io worker exhaustion

- internal/store/wal/record/packing.go
- internal/store/wal/record/packing_test.go
- internal/store/wal/record/record.go
WAL format is broken, and causes panic in recovery. (after #324)
> fix(store): broken wal format

- raft/raft.go
follower maybe send unexpected MsgAppResp to leader after new election.
> fix: send unexpected MsgAppResp to leader

- internal/raft/log/compaction_test.go
- internal/raft/log/log_test.go
- internal/raft/log/snapshot_storage_test.go
- internal/store/io/zone/segmentedfile/segmented_file_test.go
- internal/store/meta/async_test.go
- internal/store/meta/sync_test.go
- internal/store/segment/recovery_test.go
- internal/store/wal/recovery_test.go
- internal/store/wal/wal_bench_test.go
- internal/store/wal/wal_test.go
A testing cleanup. 
This pull request replaces `os.MkdirTemp` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
This saves us at least 2 lines (error check, and cleanup) on every instance.
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := os.MkdirTemp("", "")
if err != nil {
t.Fatal(err)
}
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```
> test: use `T.TempDir` to create temporary test directory

- Makefile
- build/all-in-one/Dockerfile
- build/all-in-one/config/controller.yaml
- build/all-in-one/config/gateway.yaml
- build/all-in-one/config/store.yaml
- build/all-in-one/config/timer.yaml
- build/all-in-one/config/trigger.yaml
- build/all-in-one/run.sh
- release-version.sh
Signed-off-by: wenfeng <sxian.wang@gmail.com>
Add all-in-one container for local test and quickstart
```shell
docker network create --driver bridge vanus-quickstart
docker run -d --rm \
--network vanus-quickstart \
-p 8080:8080 \
-p 8081:8081 \
--name vanus-all-in-one public.ecr.aws/vanus/all-in-one:latest
export VANUS_GATEWAY=127.0.0.1:8080
```
> build: add all-in-one container

- internal/trigger/filter/common.go
- internal/trigger/filter/exact_filter.go
- internal/trigger/filter/exact_filter_test.go
- internal/trigger/filter/prefix_filter.go
- internal/trigger/filter/suffix_filter.go
- filter exact, prefix, and suffix support event data
> feat: filter exact, prefix and suffix support event data

- internal/primitive/transform/action/strings/replace_between_positions.go
- internal/primitive/transform/action/strings/replace_between_positions_test.go
- internal/primitive/transform/common/cast.go
- internal/primitive/transform/function/strings_functions.go
- internal/primitive/transform/runtime/init.go
Issue Number: close #376
This problem solve the issue of finding a sub-string by specifying the starting position and the ending position of an existed json element, and then replace it with a specific new string.
> feat: add function replace_between_positions

- internal/timer/timingwheel/timingwheel.go
> fix(timer): cache bus writer for deliver

- internal/timer/timingwheel/timingwheel.go
> fix(timer): fix scheduled message dead cycle

- internal/store/raft/storage/compaction.go
- internal/store/raft/storage/recovery.go
- internal/store/wal/wal.go
Unexpected compaction cause corrupted metadata after restarting store.
> fix(store): unexpected compaction after restart

- internal/primitive/transform/action/strings/check_custom_values.go
- internal/primitive/transform/action/strings/check_custom_values_test.go
- internal/primitive/transform/runtime/action_bench_test.go
- internal/primitive/transform/runtime/init.go
> feat: implement function "check_custom_values"

- CONTRIBUTING.md
Issue Number: close #435 
Remove typos from the CONTRIBUTING.md file.
CONTRIBUTING.md file
> docs: remove typos from contributing file

- internal/primitive/transform/action/strings/split_with_delimiter.go
- internal/primitive/transform/action/strings/split_with_delimiter_test.go
- internal/primitive/transform/runtime/action_bench_test.go
- internal/primitive/transform/runtime/init.go
> feat: implement function "split_with_delimiter"

- internal/controller/eventbus/eventlog/eventlog_test.go
Unit test fixing of TestEventlogManager_UpdateSegmentReplicas
> test: Unit test fixing of TestEventlogManager_UpdateSegmentReplicas

- go.mod
- internal/primitive/container/conque/blocking/queue.go
- internal/primitive/executor/multi_flow.go
- internal/primitive/sync/semaphore.go
- internal/store/io/engine/psync/psync.go
- internal/store/io/engine/uring/uring.go
- internal/store/io/file.go
- internal/store/io/file_linux.go
- internal/store/io/file_other.go
- internal/store/io/stream/scheduler.go
- internal/store/io/zone/segmentedfile/recovery.go
- internal/store/io/zone/segmentedfile/segmented_file.go
- internal/store/raft/block/executor.go
- internal/store/vsb/block_open.go
- internal/store/vsb/engine_open.go
- internal/store/wal/config.go
- internal/store/wal/config_test.go
- internal/store/wal/recovery.go
- internal/store/wal/wal.go
- test/wal/walbench.go
Improve file IO performance.
Warm file after create it.
> feat(store): warm file after create

- deploy/on-premises/timer.yaml
- deploy/vanus.cn.yaml
- deploy/vanus.yaml
- internal/controller/member/member.go
- internal/timer/leaderelection/leaderelection.go
- internal/timer/leaderelection/leaderelection_test.go
fix bug for timer acquire lock failed
> fix(timer): fix bug for timer acquire lock failed

- internal/primitive/transform/action/strings/replace_between_delimiters.go
- internal/primitive/transform/action/strings/replace_between_delimiters_test.go
- internal/primitive/transform/action/strings/split_between_positions.go
- internal/primitive/transform/action/strings/split_between_positions_test.go
- internal/primitive/transform/action/strings/split_from_start.go
- internal/primitive/transform/action/strings/split_from_start_test.go
- internal/primitive/transform/function/strings_functions.go
- internal/primitive/transform/runtime/action_bench_test.go
- internal/primitive/transform/runtime/init.go
Issue Number: close #445
The function is used to scan the source JSON path from left to right, split it into an array of two sub-strings from the given numeric position of the character, and assign the array to a target JSON path. The character of the position should be included in the first sub-string (from left to right).
- added the constructor for that function
- the implementation of the function
- unit tests for that function
> feat: implement function split from start

- internal/controller/trigger/controller.go
- internal/controller/trigger/controller_test.go
- internal/controller/trigger/metadata/info.go
- internal/controller/trigger/subscription/subscription.go
- internal/controller/trigger/validation/subscripton.go
- internal/controller/trigger/validation/suscription_test.go
- internal/convert/convert.go
- vsctl/command/subscription.go
> feat: subscription create need namespace

- build/all-in-one/config/controller.yaml
- build/all-in-one/config/timer.yaml
- config/cluster/controller/node-1.yaml.example
- config/cluster/controller/node-2.yaml.example
- config/cluster/controller/node-3.yaml.example
- config/controller.yaml.example
- config/timer.yaml.example
- deploy/aws-eks/aws-eks.yml
- deploy/aws-eks/yaml/controller.yaml
- deploy/aws-eks/yaml/timer.yaml
- deploy/bare-metal/vanus.yml
- deploy/docker-compose/config/controller.yaml
- deploy/docker-compose/config/timer.yaml
- deploy/on-premises/controller.yaml
- deploy/on-premises/timer.yaml
- deploy/poc/poc.yaml
- deploy/poc/yaml/controller.yaml
- deploy/poc/yaml/timer.yaml
- deploy/vanus.cn.yaml
- deploy/vanus.yaml
> feat: the default metadata key_prefix configuration is empty

- Makefile
- build/images/root-controller/Dockerfile
- config/controller.yaml.example
- config/store.yaml.example
- deploy/aws-eks/aws-eks.yml
- deploy/aws-eks/yaml/controller.yaml
- deploy/aws-eks/yaml/etcd.yaml
- deploy/aws-eks/yaml/root-controller.yaml
- deploy/aws-eks/yaml/store.yaml
- deploy/bare-metal/vanus.yml
- deploy/basic/etcd.yaml
- deploy/basic/store.yaml
- deploy/vanus.cn.yaml
- deploy/vanus.yaml
1. fix Makefile build image error
2. fix vanus deploy config based on yaml
> fix: deploy vanus cluster based on yaml

- internal/gateway/config.go
When ports is missing from the configure file, gateway will start without listening.
Use default ports when missing.
> feat(gateway): use default ports when missing

- internal/primitive/transform/action/strings/extract_between_positions.go
- internal/primitive/transform/action/strings/extract_between_positions_test.go
- internal/primitive/transform/runtime/init.go
Issue Number: close #539
The function is used to extract value between the starting numeric position and end numeric position from the source JSON path. Then assign the value to the target JSON path.
1. Added `NewExtractBetweenPositionsAction()` constructor which returns `extractBetweenPositionsAction`
2. Implemented custom `Init()` and `Execute()` to handle 4 args.
3. Added implementation of the extraction In `Execute()`. Included four error checks.
4. Added unit tests with 7 test cases.
> feat: imple function extract between positions

- pkg/errors/utils.go
- vsctl/command/deadletter.go
- vsctl/command/event.go
- vsctl/command/eventbus.go
- vsctl/command/global.go
- vsctl/command/subscription.go
- vsctl/command/util.go
Before modification:
ubuntu@ip-172-31-55-74:~$ vsctl eventbus info xxxx
the namespace not specified, using [default] namespace
failed to query eventbus id: rpc error: code = Unknown desc = {"description":"resource not found","message":"eventbus not found","code":9400}
After modification:
ubuntu@ip-172-31-55-74:~$ ./bin/vsctl eventbus info xxxx
the namespace not specified, using [default] namespace
failed to query eventbus id: eventbus not found
> fix: error message format

- pkg/errors/utils.go
- vsctl/command/util.go
> feat: add error judgment

- pkg/cluster/auth.go
- pkg/cluster/eventbus.go
- pkg/cluster/namespace.go
- pkg/cluster/trigger.go
- pkg/errors/utils.go
convert rpcerr to ErrorType
Before modification:
```
controller       | time="2023-03-28T11:37:04Z" level=error msg="failed to create RetryEventbus, exit" error="rpc error: code = Unknown desc = {\"description\":\"volume instance not found\",\"message\":\"\",\"code\":9405}"
```
After modification
```
controller       | time="2023-03-28T11:56:22Z" level=error msg="failed to create RetryEventbus, exit" error="{\"description\": \"volume instance not found\",\"code\":9405}"
```
> fix: convert rpcerr to ErrorType

- pkg/cluster/auth.go
- pkg/cluster/eventbus.go
- pkg/cluster/namespace.go
- pkg/cluster/trigger.go
- pkg/errors/utils.go
> fix: error type conversion

- internal/controller/trigger/controller.go
- internal/controller/trigger/worker/worker.go
when  disable a subscription, the controller will send a stop command to trigger worker and modify the subscription to disabled, but it doesn't clean the memory, when the trigger worker leaves, it will schedule the subscription on the trigger worker, then the subscription will become pending and running
> fix: schedule disabled subscription when trigger worker step down

- client/internal/vanus/net/connection/connect.go
- client/pkg/eventlog/eventlog_impl.go
- internal/gateway/proxy/proxy.go
- internal/primitive/interceptor/errinterceptor/error.go
- pkg/cluster/auth.go
- pkg/cluster/eventbus.go
- pkg/cluster/namespace.go
- pkg/cluster/raw_client/conn.go
- pkg/cluster/trigger.go
- pkg/errors/utils.go
- vsctl/command/util.go
> feat: add grpc client interceptor to parse error

- internal/store/config.go
- internal/store/segment/server.go
> feat(store): use host as store address

- client/pkg/eventlog/eventlog_impl.go
> fix: query eventlog offset add start offset

- internal/controller/eventbus/controller.go
> fix: can not reclaim eventbus name

- internal/controller/config.go
- internal/controller/tenant/config.go
- internal/controller/tenant/controller.go
> feat: add config decode auto create default namespace

- Makefile
- build/images/controller/Dockerfile
- build/images/gateway/Dockerfile
- build/images/root-controller/Dockerfile
- build/images/store/Dockerfile
- build/images/timer/Dockerfile
- build/images/trigger/Dockerfile
> build: fix dockerfile

- lib/container/conque/blocking/queue.go
- lib/executor/multi_flow.go
- server/store/meta/async.go
- server/store/meta/sync.go
- server/store/meta/utils.go
- server/store/raft/block/engine.go
- server/store/raft/storage/compaction.go
- server/store/raft/storage/log_storage.go
- server/store/raft/storage/recovery.go
- server/store/raft/storage/storage.go
- server/store/raft/storage/wal.go
- server/store/wal/wal.go
> refactor: storage

- pkg/template/json/helper.go
- pkg/template/json/helper_test.go
- pkg/template/json/template_test.go
- pkg/template/text/helper.go
template does not follow the RFC3339 time format.
> fix: template does not follow RFC3339 time format

- lib/bytes/clone_go119.go
- lib/bytes/clone_go120.go
- pkg/template/json/generator.go
- pkg/template/text/parse.go
- server/store/meta/utils.go
> refactor: clone bytes

- server/trigger/client/http.go
- server/trigger/config.go
- server/trigger/reader/reader.go
- server/trigger/trigger/config.go
- server/trigger/trigger/trigger.go
- server/trigger/trigger/util.go
- server/trigger/trigger/util_test.go
- server/trigger/worker.go
> feat: trigger http protocol push event support gateway

- server/trigger/config.go
- server/trigger/trigger/trigger.go
- server/trigger/worker.go
> feat: add trigger config deadletter and order event

- pkg/template/json/generator.go
- pkg/template/json/template_test.go
JSON template renders bad empty array and empty object
- missing '[' when renders empty array
- missing '{' when renders empty object
> fix: json template render bad empty array and empty object
