internal/controller/eventbus/eventlog/eventlog.go, internal/controller/trigger/worker/manager.go, internal/controller/trigger/worker/manager_test.go, internal/controller/trigger/worker/worker.go, internal/trigger/reader/reader.go, internal/trigger/reader/reader_test.go, internal/trigger/trigger/config.go, internal/trigger/trigger/trigger.go
fix:
- clean trigger worker needs to close then stop the task
- offset is a negative which converts to uint64 is the error number
- remove no use frequency logs
-  trigger write retry and dead letter event set mas attempts to 3
=> fix: fix bug

vsctl/command/global.go
=> fix: vsctl ce port

internal/trigger/transform/template/exec.go, internal/trigger/transform/template/parse.go, internal/trigger/transform/transformer.go, internal/trigger/transform/transformer_test.go
=> feat: trigger transformer use template set data content type

internal/primitive/transform/action/render/array.go, internal/primitive/transform/action/render/array_test.go, internal/primitive/transform/arg/arg.go, internal/primitive/transform/runtime/init.go
=> feat: add function render_array

internal/primitive/transform/action/common/length.go, internal/primitive/transform/action/common/length_test.go, internal/primitive/transform/function/common_function.go, internal/primitive/transform/runtime/init.go
=> feat: add function length

internal/store/wal/wal.go
=> fix(store): pack records panic after wal recovery

internal/primitive/transform/action/source/convert_to_mongodb_sink.go, internal/primitive/transform/action/source/convert_to_mongodb_sink_test.go, internal/primitive/transform/arg/event.go, internal/primitive/transform/runtime/init.go
Signed-off-by: xdlbdy <xdlbdy@gmail.com>
- func name debezium_convert_to_mongodb_sink, args is "unique_key", "unique_value"... which must be pair apper
- event data is table column data
- must has attribute iodebeziumop which value is in [r,c,u,d]
=> feat: add debezium convert to mongodb sink

internal/primitive/transform/action/render/array_test.go, internal/primitive/transform/common/cast.go, internal/trigger/transform/transformer.go
- fix: fix transformer convert array
- transformer add panic conver
=> fix: fix transformer convert array

client/pkg/policy/policy.go
Signed-off-by: wenfeng <sxian.wang@gmail.com>
fix roundrobin policy
sort logs
=> fix: roundrobin policy

internal/store/meta/async.go
part of data in async store maybe not flush to disk.
=> fix(store): missing data in async store

internal/store/block/raft/appender.go, internal/store/io/stream/scheduler.go, internal/store/io/stream/stream.go, internal/store/wal/wal.go
After recovery, wal may be broken.
=> fix(store): break wal format after recover

internal/trigger/config.go, internal/trigger/offset/offset.go, internal/trigger/offset/offset_test.go, internal/trigger/reader/reader.go, internal/trigger/reader/reader_test.go, internal/trigger/trigger/config.go, internal/trigger/trigger/trigger.go, internal/trigger/trigger/trigger_test.go, internal/trigger/worker.go
Signed-off-by: xdlbdy <xdlbdy@gmail.com>
- add some trigger config
- offset add limit size
=> feat: add trigger config

internal/primitive/transform/action/structs/duplicate.go, internal/primitive/transform/action/structs/duplicate_test.go, internal/primitive/transform/runtime/init.go
Signed-off-by: n-kurasawa <kurasawa.nk.naohiro@gmail.com>
Issue Number: close #372
implement function "duplicate"
I implemented it as described in #372 "How to implement".
This function is used to copy the value of an existed json element, and create a new json element with that value.
=> feat: add transformer function duplicate

internal/controller/eventbus/block/block.go, internal/controller/eventbus/block/mock_block.go, internal/controller/eventbus/block/selector.go, internal/controller/eventbus/eventlog/eventlog.go, internal/controller/eventbus/eventlog/eventlog_test.go, internal/controller/eventbus/eventlog/segment.go, internal/raft/transport/host.go, internal/raft/transport/peer.go, internal/store/vsb/block_append.go, internal/store/vsb/block_read.go, internal/store/vsb/block_snapshot.go, test/benchmark/command/performance.go, test/infra/sc.yml, test/infra/vanus.yml
new raft leader balancing algorithm
1. make all segments of one eventlog have the save topology
2. slelet segmentServer that have least raft leader
=> feat: new raft leader balancing algorithm

internal/store/wal/wal_bench_test.go, internal/trigger/reader/reader.go, internal/trigger/trigger/trigger.go
Signed-off-by: xdlbdy <xdlbdy@gmail.com>
=> fix: fix remove subscription reader block

internal/gateway/proxy/proxy.go
merge the publish and send interfaces
=> feat: merge the publish and send interfaces

internal/primitive/transform/action/strings/replace_string.go, internal/primitive/transform/action/strings/replace_string_test.go, internal/primitive/transform/runtime/init.go
=> feat: add function replace string #375

CONTRIBUTING.md
Issue Number: close #400
Quickstart link in CONTRIBUTING.md is showing 404.
hyperlink is updated to https://docs.linkall.com/getting-started/quick-start
=> docs: update quickstart link in CONTRIBUTING.md

internal/controller/trigger/metadata/info.go, vsctl/command/flag.go, vsctl/command/subscription.go
Signed-off-by: xdlbdy <xdlbdy@gmail.com>
=> feat: vsctl add subscription update command

cmd/gateway/main.go, deploy/poc/poc.yaml, deploy/poc/yaml/controller.yaml, deploy/poc/yaml/gateway.yaml, deploy/poc/yaml/store.yaml, deploy/poc/yaml/timer.yaml, deploy/poc/yaml/trigger.yaml, internal/controller/eventbus/controller.go, internal/controller/eventbus/controller_test.go, internal/controller/eventbus/eventlog/eventlog.go, internal/controller/eventbus/eventlog/eventlog_test.go, internal/controller/eventbus/eventlog/mock_eventlog.go, internal/gateway/gateway.go, internal/gateway/proxy/proxy.go, observability/metrics/controller.go, observability/metrics/gateway.go, observability/metrics/label.go, observability/metrics/metrics.go
enhance metrics of controller
add metrics for prometheus
=> feat: enhance metrics of controller and gateway

build/images/controller/Dockerfile, build/images/store/Dockerfile, build/images/timer/Dockerfile, build/images/trigger/Dockerfile
=> feat: add etcdctl to image

vsctl/command/cluster.go, vsctl/command/connector.go
adjust the priority of operator endpoint
--operator-endpoint > env(VANUS_OPERATOR) > nodeip:30009
=> fix(vsctl): adjust the priority of operator endpoint

internal/primitive/transform/action/strings/capitalize_word.go, internal/primitive/transform/action/strings/capitalize_word_test.go, internal/primitive/transform/function/strings_functions.go, internal/primitive/transform/runtime/init.go
- implement function "capitalize_word"
Issue Number: close #448
- This function is used to capitalize all words in a string of an existed json element.
- added function CapitalizeWord to - internal/primitive/transform/function/strings_functions.go
- create file with function - NewCapitalizeWordAction to internal/primitive/transform/action/strings/capitalize_word.go
- create file with test - TestCapitalizeWordAction internal/primitive/transform/action/strings/capitalize_word_test.go
- register function - NewCapitalizeWordAction in vanus/internal/primitive/transform/runtime/init.go
=> feat: add Function capitalize_word and unit tests

internal/controller/eventbus/eventlog/eventlog.go, internal/controller/eventbus/eventlog/eventlog_test.go, internal/controller/eventbus/eventlog/mock_eventlog.go, internal/controller/eventbus/eventlog/segment.go, internal/controller/eventbus/eventlog/segment_test.go, test/regression/pubsub/main.go
fix blocking consumption due to unsafe concurrent issue
=> fix: blocking consumption due to unsafe concurrent issue

internal/gateway/gateway_test.go, internal/primitive/transform/action/condition/condition_if_action.go, internal/primitive/transform/common/cast.go, internal/primitive/transform/common/types.go, internal/primitive/transform/function/datatime_functions.go, internal/primitive/transform/function/math_functions.go, internal/primitive/transform/function/strings_functions.go
=> feat(trigger): split Number type of transform to Int and Float

vsctl/command/connector.go
=> fix: modify connector interface parameter types

internal/primitive/transform/action/array/unfold_array.go, internal/primitive/transform/action/array/unfold_array_test.go, internal/primitive/transform/runtime/action_bench_test.go, internal/primitive/transform/runtime/init.go
=> feat: implement function "unfold_array"

vsctl/command/cluster.go, vsctl/command/connector.go, vsctl/command/flag.go, vsctl/command/global.go, vsctl/command/util.go
1. add annotations param for connector subcommand
2. modify config structure
3. add metadata.name verification
=> feat: add annotations param for connector subcommand

internal/primitive/info/info.go, internal/primitive/transform/common/cast.go, internal/trigger/transform/transformer_test.go, internal/trigger/trigger/trigger.go
=> fix: transformer panic by cast error & add transform error log

client/client.go, client/examples/eventbus/append/main.go, client/examples/eventbus/read/main.go, client/internal/vanus/eventbus/config.go, client/internal/vanus/eventbus/name_service.go, client/mock_client.go, client/pkg/api/option.go, client/pkg/eventbus/eventbus.go, client/pkg/eventbus/lookup.go, pkg/cluster/raw_client/eventbus.go
=> feat(client): use eventbus id instead of name

internal/store/raft/block/appender.go, internal/store/raft/block/appender_transport.go, internal/store/raft/block/engine.go, internal/store/raft/transport/host.go
=> fix(store): update node endpoint

internal/controller/eventbus/controller.go, internal/controller/eventbus/controller_test.go
=> feat(eventbus): eventbus name change to id

internal/controller/eventbus/controller.go, internal/gateway/gateway.go, internal/gateway/gateway_test.go, internal/gateway/proxy/deadletter.go, internal/gateway/proxy/direct.go, internal/gateway/proxy/direct_test.go, internal/gateway/proxy/proxy.go, internal/gateway/proxy/proxy_test.go, internal/primitive/transform/common/cast.go, vsctl/command/eventbus.go
eventbus id for vsctl & gateway
=> fix: eventbus id for vsctl & gateway

internal/primitive/config.go, internal/timer/timingwheel/bucket_test.go, internal/timer/timingwheel/timingwheel_test.go, internal/trigger/filter/prefix_filter.go, internal/trigger/filter/suffix_filter.go
=> fix: fix ut and golint

cmd/controller/main.go, config/controller.yaml.example, internal/controller/config.go, internal/controller/member/config.go, internal/controller/member/member.go, internal/controller/member/mock_member.go, internal/gateway/proxy/proxy.go, internal/primitive/subscription.go, internal/primitive/transform/action/array/render_test.go, internal/primitive/vanus/id.go, vsctl/command/cluster.go, vsctl/command/connector.go, vsctl/command/eventbus.go
=> feat: enhance leader election

internal/controller/eventbus/block/block_test.go, internal/gateway/proxy/proxy.go, internal/kv/constant.go, internal/timer/timingwheel/bucket.go, internal/timer/timingwheel/bucket_test.go, internal/trigger/trigger/trigger.go
=> feat: change deliverytime type to ce timestamp

internal/timer/timingwheel/timingwheel.go
=> fix: fix event dst eventbus check

internal/controller/eventbus/controller.go, internal/controller/eventbus/eventlog/eventlog.go, internal/controller/eventbus/eventlog/eventlog_test.go, internal/controller/eventbus/server/mock_instance.go, internal/controller/trigger/storage/offset.go, internal/store/block/raw/engine.go, internal/store/block/raw/engine_test.go, internal/store/block/testing/mock_block.go, internal/store/raft/block/appender.go, internal/store/raft/storage/log_storage.go, internal/store/segment/server.go, internal/store/vsb/engine_recover_test.go, internal/trigger/filter/suffix_filter_test.go, internal/trigger/filter/trigger_filter_test.go, proto/proto/controller.proto, proto/proto/segment.proto, raft/confchange/confchange.go, raft/doc.go, raft/node.go, raft/quorum/majority.go, raft/quorum/quorum.go, raft/raft.go, raft/raftpb/raft.pb.go, raft/rafttest/interaction_env_handler_add_nodes.go, raft/status.go, test/benchmark/command/component.go, vsctl/command/event.go
=> fix: revert unexpected change of ID

deploy/aws-eks/yaml/controller.yaml, deploy/bare-metal/vanus.yml, deploy/on-premises/controller.yaml, deploy/vanus.yaml, pkg/cluster/raw_client/conn.go
1. fix controller start failed
2. fix conn log print
=> fix: fix bug for cluster deploy failed

pkg/cluster/eventbus.go, vsctl/command/eventbus.go, vsctl/command/subscription.go
=> feat: subscription create default namespace

internal/timer/metadata/key.go, internal/timer/timingwheel/bucket.go, internal/timer/timingwheel/timingwheel.go
=> feat: modify timer etcd key

vsctl/command/cluster.go
=> feat: modify the default version supported by vsctl

build/all-in-one/config/store.yaml, cmd/store/main.go, config/store.yaml.example, deploy/aws-eks/aws-eks.yml, deploy/aws-eks/yaml/store.yaml, deploy/bare-metal/vanus.yml, deploy/basic/store.yaml, deploy/vanus.yaml, internal/store/config.go
=> feat(store): remove unused snowflake

vsctl/command/cluster.go, vsctl/command/connector.go, vsctl/command/flag.go, vsctl/command/global.go
=> feat: modify the cluster api params to annotations

vsctl/command/cluster.go
=> fix: vsctl cluster spec info error

vsctl/command/cluster.go, vsctl/command/connector.go
=> feat: update vanus operator filename

vsctl/command/cluster.go, vsctl/command/global.go
=> feat: add custom configuration item

internal/gateway/gateway.go, pkg/cluster/controller.go, pkg/cluster/eventbus.go, pkg/cluster/namespace.go, test/metadata/main.go, vsctl/command/event.go
change gateway cloudevents path
use `/namespaces/:namespace_name/eventbus/:eventbus_name/events`
=> feat: change gateway cloudevents path

internal/gateway/gateway.go, internal/gateway/gateway_test.go
=> feat: fix gateway ut error

internal/primitive/transform/action/strings/extract_between_delimiters_test.go, internal/primitive/transform/action/strings/extract_between_positions.go
=> feat: fix golangci error

internal/controller/trigger/storage/offset.go
=> fix: metadata offset key

README.md
I left VanusCloud without a space.
=> fix: changed bad link to vanus cloud

client/pkg/eventbus/eventbus.go
=> fix(client): watcher not closed after eventbus deletion

client/pkg/eventbus/eventbus.go
=> Revert "fix(client): watcher not closed after eventbus deletion"

vsctl/command/cluster.go, vsctl/command/global.go
=> feat: add container resources param for cluster subcommand

deploy/docker-compose/config/prometheus.yml, deploy/docker-compose/config/root-controller.yaml, deploy/docker-compose/docker-compose.yml
=> feat: update docker compose

internal/trigger/offset/offset.go
=> fix: trigger offset bug

observability/log/log.go
=> feat: export `With` and `Output` of logger

client/internal/vanus/net/connection/connect.go, cmd/controller/main.go, cmd/root/main.go, internal/gateway/proxy/proxy.go, internal/store/segment/server.go, pkg/cluster/raw_client/conn.go, pkg/grpc/interceptor/errors/error.go, pkg/grpc/interceptor/errors/error_test.go
=> fix: package structure of error interceptor

pkg/grpc/interceptor/errors/error.go, vsctl/command/util.go
=> fix: return nil from error client interceptor

internal/store/raft/storage/compaction.go, internal/store/raft/storage/compaction_test.go, internal/store/raft/storage/recovery.go, internal/store/raft/storage/snapshot_storage_test.go, internal/store/raft/storage/storage_test.go, internal/store/raft/storage/wal.go
=> fix(store): unexpected compaction after restart

client/pkg/eventlog/eventlog_impl.go
=> fix: query eventlog offset add start offset

deploy/bare-metal/vanus.yml, deploy/basic/controller.yaml, deploy/basic/etcd.yaml, deploy/basic/gateway.yaml, deploy/basic/root-controller.yaml, deploy/basic/store.yaml, deploy/basic/timer.yaml, deploy/basic/trigger.yaml, deploy/docker-compose/docker-compose.yml, deploy/vanus.cn.yaml, deploy/vanus.yaml
=> feat: update deploy yaml

internal/primitive/json/path/parse.go
=> fix: parse wildcard selector

README.md, client/go.mod, deploy/aws-eks/aws-eks.yml, deploy/aws-eks/yaml/controller.yaml, deploy/aws-eks/yaml/gateway.yaml, deploy/aws-eks/yaml/root-controller.yaml, deploy/aws-eks/yaml/store.yaml, deploy/aws-eks/yaml/timer.yaml, deploy/aws-eks/yaml/trigger.yaml, deploy/bare-metal/vanus.yml, deploy/basic/controller.yaml, deploy/basic/gateway.yaml, deploy/basic/root-controller.yaml, deploy/basic/store.yaml, deploy/basic/timer.yaml, deploy/basic/trigger.yaml, deploy/docker-compose/docker-compose.yml, deploy/vanus.cn.yaml, deploy/vanus.yaml, go.mod, observability/tracing/tracing.go, pkg/go.mod, proto/go.mod, release-version.sh, vsctl/command/cluster.go
=> chore: bump version to v0.9.0

.github/workflows/docker-build.yml
=> build: prevent pushing docker image to tencent cloud

internal/gateway/proxy/direct.go
=> fix(gateway): can not marshal response from ValidateEventbus

client/internal/eventbus/name_service.go, client/internal/eventlog/name_service.go, client/pkg/policy/policy.go
eventlog routing failed due to policy cache
=> fix(client): eventlog routing failed

internal/primitive/template/text/parse.go
=> fix: parse text template with escaped char

client/internal/net/connection/connect.go
=> feat: add grpc recv msg size

internal/trigger/trigger/trigger.go, observability/metrics/label.go, observability/metrics/trigger.go
=> feat: add trigger push event counter metric label

internal/trigger/reader/reader.go
=> feat: trigger find new event log and fix offset under flow error

tool/vsctl/command/cluster.go, tool/vsctl/command/connector.go, tool/vsctl/command/subscription.go
=> chore: remove refs to deprecated io/ioutil
